name: Build & Release

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
        
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - run: flutter pub get
      - run: flutter build ios --no-codesign
      - run: |
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - run: flutter pub get
      - run: flutter build web

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            pkg-config \
            clang \
            ninja-build \
            libgtk-3-dev \
            libblkid-dev \
            liblzma-dev \
            liblz4-dev \
            libssl-dev \
            libprotobuf-dev \
            protobuf-compiler
      - run: flutter pub get
      - run: flutter build linux

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - run: flutter pub get
      - run: flutter build macos

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - run: flutter pub get
      - run: flutter build windows

  release:
    runs-on: ubuntu-latest
    needs: [build-android, build-ios, build-web, build-linux, build-macos, build-windows]
    steps:
      - uses: actions/checkout@v3
      - name: Gather Artifacts
        run: |
          ls
          mkdir -p release
          cp -r build/app/outputs/flutter-apk/*.apk release/
          cp build/ios/iphoneos/app.ipa release/
          cp -r build/web/* release/
          cp -r build/linux/x64/release/bundle/* release/
          cp -r build/macos/Build/Products/Release/*.app release/
          cp -r build/windows/x64/runner/Release/*.exe release/

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/*
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}