name: Test

# Gist author: https://gist.github.com/aagarwal1012
# Gist link: https://gist.github.com/aagarwal1012/eb2551683d81cf47d60868ab607520b1

# The following gist has been slightly modified to test on linux instead of apk

# This workflow is triggered on pushes to the repository.

on:
  pull_request:
    branches: [main, development]
  push:
    branches: [main, development]
    
# on: push    # Default will running for every branch.
    
jobs:
  test:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            pkg-config \
            clang \
            ninja-build \
            libgtk-3-dev \
            libblkid-dev \
            liblzma-dev \
            liblz4-dev \
            libssl-dev \
            libprotobuf-dev \
            protobuf-compiler
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter test